site_name: 蝴蝶之吻
nav:
  - 甘特图: index.md
  - 团队管理: team.md
  - 团队生存法则: team/team1.md
  - 团灭: team/team2.md
  - 团长: team/team3.md
theme: material
extra:
  palette:
    primary: 'cyan'
    accent: 'purple'
extra_javascript:
  - https://unpkg.com/mermaid@7.1.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - js/umlconvert.js
markdown_extensions:
  - toc
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences: [
            {name: flow, class: uml-flowchart}
           ,{name: sequence, class: uml-sequence-diagram}
           ,{name: mermaid, class: uml-mermaid}
      ]
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
